# Streamlit configuration for server and theme

[server]
# Allow large uploads (in MB) — effectively no limit
maxUploadSize = 20000

[theme]
# Custom UI theme for a polished look
primaryColor = "#10B981"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"
baseFontSize = 16





