name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Render of new deploy
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
