# .streamlit/config.toml
[server]
maxUploadSize = 20000  # in MB, effectively no limit

[theme]
primaryColor = "#10B981"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"
baseFontSize = 16






