\[server]

# Increase the maximum upload size to effectively unlimited (in MB)

# Server settings to remove upload caps

maxUploadSize = 20000  # in MB, effectively unlimited

\[theme]

# Custom UI theme colors and fonts

primaryColor = "#10B981"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"
baseFontSize = 16





