[server]
# Effectively remove any upload limit (in MB)
maxUploadSize = 20000

[theme]
primaryColor = "#10B981"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"
baseFontSize = 16



